#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys
import argparse

import roman

def main():
    ap = argparse.ArgumentParser()
    ap.parse_args()
    prog = ap.prog
    for s in sys.stdin:
        s = s.strip()
        try:
            i = roman.fromRoman(s.upper())
        except roman.InvalidRomanNumeralError:
            try:
                i = int(s, 0)
            except ValueError:
                print(f'{prog}: invalid numeral: {s!r}', file=sys.stderr)
                continue
        print(i)
if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
